### ISSUE TITLE
Streaming as words are generated?

### ISSUE THREAD

**Issue by sion42x** [BuffMcBigHuge/text-generation-webui-edge-tts#10]
Hi, great job on this and it works GREAT on my phi-2 chatbot for Orange Pi 5 Plus project! 

Is it possible to implement streaming (see https://github.com/rany2/edge-tts/blob/master/examples/basic_audio_streaming.py) to have the API called and read as text is generated?

**Comment by BuffMcBigHuge** [comment]
Hey @sion42x, I'm sure it can be implemented, however streaming it along with RVC wouldn't be easy, which seems to be the primary use case of this extension.
