### ISSUE TITLE
internet connection

### ISSUE THREAD

**Issue by kalle07** [BuffMcBigHuge/text-generation-webui-edge-tts#9]
please tell me exactly why this is nessesary and what is submitted.

in each conversation step aprox 1MB is transferd if i block my internet this error:
Cannot connect to host speech.platform.bing.com:443 ssl:<ssl.SSLContext object at 0x000001C3F8C0BCC0> [getaddrinfo failed]

**Comment by BuffMcBigHuge** [comment]
The [edge_tts library](https://github.com/rany2/edge-tts) used in this extension is an API request without a key to Microsoft Edge online TTS. The text that is generated from ooba is sent to Microsoft's servers which returns the audio which is then fed into RVC.

**Comment by kalle07** [comment]
ok and why you have this extention .. all want offline !!!

**Comment by BuffMcBigHuge** [comment]
The reason why I used edge_tts for RVC is because it's the fastest I found with the highest quality. RVC can be added to any other TTS system include offline, but the latency and quality will suffer.

**Comment by kalle07** [comment]
i see...

https://github.com/kanttouchthis/text_generation_webui_xtts
maybe you take a look, its okay and offline
